### ISSUE TITLE
`getStorageAt` calls are too slow

### ISSUE THREAD

**Issue by prathamesh0** [vulcanize/ipld-eth-server#200] opened 2022-10-17 11:54 UTC
- The `getStorageAt` API is served over GQL and RPC endpoints using the same query 
- The [query](https://github.com/cerc-io/ipld-eth-server/blob/release-v4.2.0-alpha/pkg/eth/ipld_retriever.go#L236) used to satisfy the call is too slow
  - Eg. In one instance, it takes `~2.5` mins to get the result - https://gist.github.com/prathamesh0/388f7ab285c8cc173d7744726827a5f4

**Comment by i-norden** [comment] 2022-11-03 13:25
This looks to be caused by the inability to direct to the query to the appropriate partition as well. Although the fix is not as simple as providing a block_number to direct to a partition as it is in other queries, because we don't know which block_number the latest storage value for a given slot is at.

**Comment by AFDudley** [comment] 2023-06-10 16:13
Resolved in https://github.com/cerc-io/ipld-eth-db/pull/116

**Closed as completed by AFDudley** 2023-06-10 16:13 UTC
